name: CI – pro_venv + per-form tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      # === التشغيل القديم كما هو (Bootstrap via pro_venv.py) ===
      - name: Install minimal requirements (legacy step)
        run: |
          python -m pip install --upgrade pip

      - name: Run pro_venv.py (legacy bootstrap)
        run: |
          python pro_venv.py

      # === خطوات الاختبار الجديدة ===
      - name: Install project requirements for tests
        run: |
          pip install -r requirements.txt pytest

      - name: Generate per-form tests
        run: |
          python tools/gen_tests.py

      - name: Run pytest
        run: |
          pytest -q
